---
swagger: "2.0"
info:
  description: "A sample API that uses a petstore as an example to demonstrate features\
    \ in the swagger-2.0 specification"
  version: "1.0.0"
  title: "Swagger herrero-cerrajero-api"
  termsOfService: "http://helloreverb.com/terms/"
  contact:
    name: "Herrero Cerrajero"
    url: "https://herrero-cerrajero.herokuapp.com"
    email: "herrerocerrajero@gmail.com"
  license:
    name: "MIT"
    url: "http://opensource.org/licenses/MIT"
host: "localhost:8080"
basePath: "/api/v1"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /ncuentas:
    get:
      tags:
      - "ncuentas"
      description: "Devuelve los números de cuentas"
      operationId: "getCuentas"
      parameters: 
      - name: "idAdmin"
        in: "query"
        description: "Nombre de administrador"
        required: false
        type: "string"        
      - name: "direccion"
        in: "query"
        description: "Dirección"
        required: false
        type: "string"               
      responses:
        200:
          description: "Cuentas response"
          schema:
            type: "array"
            title: "Ncuentas"
            items:
              $ref: "#/definitions/Ncuentas"
        404:
          description: "Not found"
        500:
          description: "Internal Server Error"
      x-swagger-router-controller: "Ncuentas"
    post:
      tags:
      - "ncuentas"
      description: "Añadir nuevo número de cuenta"
      operationId: "insertCuenta"
      parameters:
      - name: "ncuenta"
        in: body
        description: "Número de cuenta que se quiere añadir en JSON"
        required: true
        schema: 
          title: "Ncuentas"
          type: "array"
          items:
            $ref: "#/definitions/Ncuentas"      
      responses:
        201:
          description: "Created"
        400:
          description: "Bad request"
        409:
          description: "Conflict"
        422:
          description: "Unprocessable Entity"
        500:
          description: "Internal Server Error"
      x-swagger-router-controller: "Ncuentas"    
  /ncuentas/last:
    get:
      tags:
      - "ncuentas"
      description: "Devuelve el último número de cuenta añadido"
      operationId: "getCuentaLast"
      parameters: []
      responses:
        200:
          description: "Cuentas response"
          schema:
            type: "array"
            title: "Ncuentas"
            items:
              $ref: "#/definitions/Ncuentas"
        500:
          description: "Internal Server Error"
      x-swagger-router-controller: "Ncuentas"
  /ncuentas/{idAdmin}/{direccion}:
    put:
      tags:
      - "ncuentas"
      description: "Actualiza el número de cuenta dado"
      operationId: "updateCuenta"
      parameters:
      - name: "idAdmin"
        in: "path"
        description: "Nombre de administrador"
        required: true
        type: "string"        
      - name: "direccion"
        in: "path"
        description: "Dirección"
        required: true
        type: "string"        
      - name: "ncuenta"
        in: body
        description: "Número de cuenta que se quiere actualizar en JSON"
        required: true
        schema: 
          title: "Ncuentas"
          type: "array"
          items:
            $ref: "#/definitions/Ncuentas"    
      responses:
        200:
          description: "Updated"
        400:
          description: "Bad request"
        404: 
          description: "Not found"
        422:
          description: "Unprocessable Entity"
        500:
          description: "Internal Server Error"    
      x-swagger-router-controller: "Ncuentas"     
    delete:
      tags:
      - "ncuentas"
      description: "Borra un número de cuenta dado"
      operationId: "deleteCuenta"
      parameters:
      - name: "idAdmin"
        in: "path"
        description: "Nombre de administrador"
        required: true
        type: "string"        
      - name: "direccion"
        in: "path"
        description: "Dirección"
        required: true
        type: "string"           
      responses:
        204:
          description: "Deleted"
        404: 
          description: "Not found"
        500:
          description: "Internal Server Error"    
      x-swagger-router-controller: "Ncuentas"    
  /facturas:
    get:
      tags:
      - "facturas"
      description: "Devuelve todas las facturas"
      operationId: "getFacturas"
      parameters: 
      - name: "idAdmin"
        in: "query"
        description: "Nombre de administrador"
        required: false
        type: "string"        
      - name: "direccion"
        in: "query"
        description: "Dirección"
        required: false
        type: "string"               
      responses:
        200:
          description: "Facturas response"
          schema:
            type: "array"
            title: "Ncuentas"
            items:
              $ref: "#/definitions/Facturas"
        404:
          description: "Not found"
        500:
          description: "Internal Server Error"
      x-swagger-router-controller: "Facturas"        
    post:
      tags:
      - "facturas"
      description: "Añadir nueva factura"
      operationId: "insertFactura"
      parameters:
      - name: "factura"
        in: body
        description: "Factura que se quiere añadir en JSON"
        required: true
        schema: 
          title: "Facturas"
          type: "array"
          items:
            $ref: "#/definitions/Facturas"      
      responses:
        201:
          description: "Created"
        400:
          description: "Bad request"
        409:
          description: "Conflict"
        422:
          description: "Unprocessable Entity"
        500:
          description: "Internal Server Error"
      x-swagger-router-controller: "Facturas"    
  /facturas/{numero}:
    put:
      tags:
      - "facturas"
      description: "Actualiza una factura dada"
      operationId: "updateFactura"
      parameters:
      - name: "numero"
        in: "path"
        description: "Numero de factura"
        required: true
        type: "string"         
      - name: "factura"
        in: body
        description: "Factura que se quiere actualizar en JSON"
        required: true
        schema: 
          title: "Facturas"
          type: "array"
          items:
            $ref: "#/definitions/Facturas"     
      responses:
        200:
          description: "Updated"
        400:
          description: "Bad request"
        404: 
          description: "Not found"
        422:
          description: "Unprocessable Entity"
        500:
          description: "Internal Server Error"    
      x-swagger-router-controller: "Facturas"   
    delete:
      tags:
      - "facturas"
      description: "Borra una factura dada"
      operationId: "deleteFactura"
      parameters:
      - name: "numero"
        in: "path"
        description: "Numero de factura"
        required: true
        type: "string"                 
      responses:
        204:
          description: "Deleted"
        404: 
          description: "Not found"
        500:
          description: "Internal Server Error"    
      x-swagger-router-controller: "Facturas"                        
definitions:
  Ncuentas:
    type: "object"
    properties:
      idAdmin:
        type: "string"
      direccion:
        type: "string"
      iban:
        type: "string"
      nif:
        type: "string"
      referencia:
        type: "string"
  Facturas:
    type: "object"
    properties:
      fecha:
        type: "string"
      idAdmin:
        type: "string"
      direccion:
        type: "string"
      numero:
        type: "string"
      estado:
        type: "string"     
